[package]
name = "anchor2d"
description = "A simple anchoring library"
license = "MIT OR Apache-2.0"
version = "0.1.7"
edition = "2024"
repository = "https://github.com/JMANN240/anchor2d"

[dependencies]
glam = "0.30.5"
